publish_to: none
name: cloud_firestore_odm_generator
description: A code generator for cloud_firestore_odm.
homepage: https://firebase.flutter.dev/docs/firestore/odm
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.0.0-dev.90

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.4
  build_config: ^1.2.0
  cloud_firestore_odm:
    git:
      url: https://github.com/dieringe/firestoreodm-flutter
      ref: 87c3be54480f12535b788f24adfd09ec9554d292
      path: packages/cloud_firestore_odm
  collection: ^1.19.1
  freezed_annotation: ^3.1.0
  # Can be removed once this is fixed https://github.com/dart-lang/graphs/issues/86
  graphs: ^2.3.2
  json_annotation: ^4.9.0
  meta: ^1.17.0
  recase: ^4.1.0
  source_gen: ^4.2.0
  source_helper: ^1.3.10

dev_dependencies:
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
