name: cloud_firestore_odm
description: An ODM for Firebase Cloud Firestore (cloud_firestore).
homepage: https://github.com/firebaseextended/firestoreodm-flutter
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.0.0-dev.88

false_secrets:
  - example/**

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.1.2
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
